services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
  backend:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - authentication
      - booking
      - entertainment
      - payment
      - user
  authentication:
    build: ./authentication
    ports:
      - "3001:3000"
    volumes:
      - ./authentication:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - authentication_database
  authentication_database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "authentication-data:/data/db"
  booking:
    build: ./booking
    ports:
      - "3002:3000"
    volumes:
      - ./booking:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - booking_database
  booking_database:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - "booking-data:/data/db"
  entertainment:
    build: ./entertainment
    ports:
      - "3003:3000"
    volumes:
      - ./entertainment:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - entertainment_database
  entertainment_database:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - "entertainment-data:/data/db"
  payment:
    build: ./payment
    ports:
      - "3004:3000"
    volumes:
      - ./payment:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - payment_database
  payment_database:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - "payment-data:/data/db"
  user:
    build: ./user
    ports:
      - "3005:3000"
    volumes:
      - ./user:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - user_database
  user_database:
    image: mongo:latest
    ports:
      - "27021:27017"
    volumes:
      - "user-data:/data/db"

volumes:
  authentication-data:
  booking-data:
  entertainment-data:
  payment-data:
  user-data:
